---
- hosts: test-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: install docker-compose
    command: sudo apt install -y docker-compose
  
  - name: deploying bank app 
    command: docker run -itd -p 8080:8080 rohith2703/bankingcapstone:1.0

  - name: deploy node exporter
    command: docker run -itd -p 9100:9100 prom/node-exporter