---
- hosts: test-server
  become: true
  become_user: root
  remote_user: ubuntu
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: install docker-compose
    command: sudo apt install docker-compose
  
  - name: deploying bank app and node-exporter
    command: docker-compose up